export const countries = [
  {
    code: "AF",
    name_en: "Afghanistan",
    name_de: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    code: "AL",
    name_en: "Albania",
    name_de: "Albanien",
    flag: "🇦🇱",
  },
  {
    code: "DZ",
    name_en: "Algeria",
    name_de: "Algerien",
    flag: "🇩🇿",
  },
  {
    code: "AS",
    name_en: "American Samoa",
    name_de: "Amerikanisch-Samoa",
    flag: "🇦🇸",
  },
  {
    code: "AD",
    name_en: "Andorra",
    name_de: "Andorra",
    flag: "🇦🇩",
  },
  {
    code: "AO",
    name_en: "Angola",
    name_de: "Angola",
    flag: "🇦🇴",
  },
  {
    code: "AI",
    name_en: "Anguilla",
    name_de: "Anguilla",
    flag: "🇦🇮",
  },
  {
    code: "AG",
    name_en: "Antigua and Barbuda",
    name_de: "Antigua und Barbuda",
    flag: "🇦🇬",
  },
  {
    code: "AR",
    name_en: "Argentina",
    name_de: "Argentinien",
    flag: "🇦🇷",
  },
  {
    code: "AM",
    name_en: "Armenia",
    name_de: "Armenien",
    flag: "🇦🇲",
  },
  {
    code: "AW",
    name_en: "Aruba",
    name_de: "Aruba",
    flag: "🇦🇼",
  },
  {
    code: "AU",
    name_en: "Australia",
    name_de: "Australien",
    flag: "🇦🇺",
  },
  {
    code: "AT",
    name_en: "Austria",
    name_de: "Österreich",
    flag: "🇦🇹",
  },
  {
    code: "AZ",
    name_en: "Azerbaijan",
    name_de: "Aserbaidschan",
    flag: "🇦🇿",
  },
  {
    code: "BS",
    name_en: "Bahamas",
    name_de: "Bahamas",
    flag: "🇧🇸",
  },
  {
    code: "BH",
    name_en: "Bahrain",
    name_de: "Bahrain",
    flag: "🇧🇭",
  },
  {
    code: "BD",
    name_en: "Bangladesh",
    name_de: "Bangladesch",
    flag: "🇧🇩",
  },
  {
    code: "BB",
    name_en: "Barbados",
    name_de: "Barbados",
    flag: "🇧🇧",
  },
  {
    code: "BY",
    name_en: "Belarus",
    name_de: "Weißrussland",
    flag: "🇧🇾",
  },
  {
    code: "BE",
    name_en: "Belgium",
    name_de: "Belgien",
    flag: "🇧🇪",
  },
  {
    code: "BZ",
    name_en: "Belize",
    name_de: "Belize",
    flag: "🇧🇿",
  },
  {
    code: "BJ",
    name_en: "Benin",
    name_de: "Benin",
    flag: "🇧🇯",
  },
  {
    code: "BM",
    name_en: "Bermuda",
    name_de: "Bermuda",
    flag: "🇧🇲",
  },
  {
    code: "BT",
    name_en: "Bhutan",
    name_de: "Bhutan",
    flag: "🇧🇹",
  },
  {
    code: "BO",
    name_en: "Bolivia",
    name_de: "Bolivien",
    flag: "🇧🇴",
  },
  {
    code: "BA",
    name_en: "Bosnia and Herzegovina",
    name_de: "Bosnien und Herzegowina",
    flag: "🇧🇦",
  },
  {
    code: "BW",
    name_en: "Botswana",
    name_de: "Botswana",
    flag: "🇧🇼",
  },
  {
    code: "BR",
    name_en: "Brazil",
    name_de: "Brasilien",
    flag: "🇧🇷",
  },
  {
    code: "IO",
    name_en: "British Indian Ocean Territory",
    name_de: "Britisches Territorium im Indischen Ozean",
    flag: "🇮🇴",
  },
  {
    code: "VG",
    name_en: "British Virgin Islands",
    name_de: "Britische Jungferninseln",
    flag: "🇻🇬",
  },
  {
    code: "BN",
    name_en: "Brunei",
    name_de: "Brunei",
    flag: "🇧🇳",
  },
  {
    code: "BG",
    name_en: "Bulgaria",
    name_de: "Bulgarien",
    flag: "🇧🇬",
  },
  {
    code: "BF",
    name_en: "Burkina Faso",
    name_de: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    code: "BI",
    name_en: "Burundi",
    name_de: "Burundi",
    flag: "🇧🇮",
  },
  {
    code: "KH",
    name_en: "Cambodia",
    name_de: "Kambodscha",
    flag: "🇰🇭",
  },
  {
    code: "CM",
    name_en: "Cameroon",
    name_de: "Kamerun",
    flag: "🇨🇲",
  },
  {
    code: "CA",
    name_en: "Canada",
    name_de: "Kanada",
    flag: "🇨🇦",
  },
  {
    code: "CV",
    name_en: "Cape Verde",
    name_de: "Kap Verde",
    flag: "🇨🇻",
  },
  {
    code: "KY",
    name_en: "Cayman Islands",
    name_de: "Kaimaninseln",
    flag: "🇰🇾",
  },
  {
    code: "CF",
    name_en: "Central African Republic",
    name_de: "Zentralafrikanische Republik",
    flag: "🇨🇫",
  },
  {
    code: "TD",
    name_en: "Chad",
    name_de: "Tschad",
    flag: "🇹🇩",
  },
  {
    code: "CL",
    name_en: "Chile",
    name_de: "Chile",
    flag: "🇨🇱",
  },
  {
    code: "CN",
    name_en: "China",
    name_de: "China",
    flag: "🇨🇳",
  },
  {
    code: "CO",
    name_en: "Colombia",
    name_de: "Kolumbien",
    flag: "🇨🇴",
  },
  {
    code: "KM",
    name_en: "Comoros",
    name_de: "Komoren",
    flag: "🇰🇲",
  },
  {
    code: "CG",
    name_en: "Congo",
    name_de: "Kongo",
    flag: "🇨🇬",
  },
  {
    code: "CD",
    name_en: "Democratic Republic of the Congo",
    name_de: "Demokratische Republik Kongo",
    flag: "🇨🇩",
  },
  {
    code: "CK",
    name_en: "Cook Islands",
    name_de: "Cookinseln",
    flag: "🇨🇰",
  },
  {
    code: "CR",
    name_en: "Costa Rica",
    name_de: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    code: "CI",
    name_en: "Ivory Coast",
    name_de: "Elfenbeinküste",
    flag: "🇨🇮",
  },
  {
    code: "HR",
    name_en: "Croatia",
    name_de: "Kroatien",
    flag: "🇭🇷",
  },
  {
    code: "CU",
    name_en: "Cuba",
    name_de: "Kuba",
    flag: "🇨🇺",
  },
  {
    code: "CY",
    name_en: "Cyprus",
    name_de: "Zypern",
    flag: "🇨🇾",
  },
  {
    code: "CZ",
    name_en: "Czech Republic",
    name_de: "Tschechische Republik",
    flag: "🇨🇿",
  },
  {
    code: "DK",
    name_en: "Denmark",
    name_de: "Dänemark",
    flag: "🇩🇰",
  },
  {
    code: "DJ",
    name_en: "Djibouti",
    name_de: "Dschibuti",
    flag: "🇩🇯",
  },
  {
    code: "DM",
    name_en: "Dominica",
    name_de: "Dominica",
    flag: "🇩🇲",
  },
  {
    code: "DO",
    name_en: "Dominican Republic",
    name_de: "Dominikanische Republik",
    flag: "🇩🇴",
  },
  {
    code: "EC",
    name_en: "Ecuador",
    name_de: "Ecuador",
    flag: "🇪🇨",
  },
  {
    code: "EG",
    name_en: "Egypt",
    name_de: "Ägypten",
    flag: "🇪🇬",
  },
  {
    code: "SV",
    name_en: "El Salvador",
    name_de: "El Salvador",
    flag: "🇸🇻",
  },
  {
    code: "GQ",
    name_en: "Equatorial Guinea",
    name_de: "Äquatorialguinea",
    flag: "🇬🇶",
  },
  {
    code: "ER",
    name_en: "Eritrea",
    name_de: "Eritrea",
    flag: "🇪🇷",
  },
  {
    code: "EE",
    name_en: "Estonia",
    name_de: "Estland",
    flag: "🇪🇪",
  },
  {
    code: "SZ",
    name_en: "Eswatini",
    name_de: "Eswatini",
    flag: "🇸🇿",
  },
  {
    code: "ET",
    name_en: "Ethiopia",
    name_de: "Äthiopien",
    flag: "🇪🇹",
  },
  {
    code: "FK",
    name_en: "Falkland Islands",
    name_de: "Falklandinseln",
    flag: "🇫🇰",
  },
  {
    code: "FO",
    name_en: "Faroe Islands",
    name_de: "Färöer Inseln",
    flag: "🇫🇴",
  },
  {
    code: "FJ",
    name_en: "Fiji",
    name_de: "Fidschi",
    flag: "🇫🇯",
  },
  {
    code: "FI",
    name_en: "Finland",
    name_de: "Finnland",
    flag: "🇫🇮",
  },
  {
    code: "FR",
    name_en: "France",
    name_de: "Frankreich",
    flag: "🇫🇷",
  },
  {
    code: "GF",
    name_en: "French Guiana",
    name_de: "Französisch-Guayana",
    flag: "🇬🇫",
  },
  {
    code: "PF",
    name_en: "French Polynesia",
    name_de: "Französisch-Polynesien",
    flag: "🇵🇫",
  },
  {
    code: "TF",
    name_en: "French Southern Territories",
    name_de: "Französische Süd- und Antarktisgebiete",
    flag: "🇹🇫",
  },
  {
    code: "GA",
    name_en: "Gabon",
    name_de: "Gabun",
    flag: "🇬🇦",
  },
  {
    code: "GM",
    name_en: "Gambia",
    name_de: "Gambia",
    flag: "🇬🇲",
  },
  {
    code: "GE",
    name_en: "Georgia",
    name_de: "Georgien",
    flag: "🇬🇪",
  },
  {
    code: "DE",
    name_en: "Germany",
    name_de: "Deutschland",
    flag: "🇩🇪",
  },
  {
    code: "GH",
    name_en: "Ghana",
    name_de: "Ghana",
    flag: "🇬🇭",
  },
  {
    code: "GI",
    name_en: "Gibraltar",
    name_de: "Gibraltar",
    flag: "🇬🇮",
  },
  {
    code: "GR",
    name_en: "Greece",
    name_de: "Griechenland",
    flag: "🇬🇷",
  },
  {
    code: "GL",
    name_en: "Greenland",
    name_de: "Grönland",
    flag: "🇬🇱",
  },
  {
    code: "GD",
    name_en: "Grenada",
    name_de: "Grenada",
    flag: "🇬🇩",
  },
  {
    code: "GP",
    name_en: "Guadeloupe",
    name_de: "Guadeloupe",
    flag: "🇬🇵",
  },
  {
    code: "GU",
    name_en: "Guam",
    name_de: "Guam",
    flag: "🇬🇺",
  },
  {
    code: "GT",
    name_en: "Guatemala",
    name_de: "Guatemala",
    flag: "🇬🇹",
  },
  {
    code: "GG",
    name_en: "Guernsey",
    name_de: "Guernsey",
    flag: "🇬🇬",
  },
  {
    code: "GN",
    name_en: "Guinea",
    name_de: "Guinea",
    flag: "🇬🇳",
  },
  {
    code: "GW",
    name_en: "Guinea-Bissau",
    name_de: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    code: "GY",
    name_en: "Guyana",
    name_de: "Guyana",
    flag: "🇬🇾",
  },
  {
    code: "HT",
    name_en: "Haiti",
    name_de: "Haiti",
    flag: "🇭🇹",
  },
  {
    code: "HM",
    name_en: "Heard Island and McDonald Islands",
    name_de: "Heard- und McDonald-Inseln",
    flag: "🇭🇲",
  },
  {
    code: "HN",
    name_en: "Honduras",
    name_de: "Honduras",
    flag: "🇭🇳",
  },
  {
    code: "HK",
    name_en: "Hong Kong",
    name_de: "Hongkong",
    flag: "🇭🇰",
  },
  {
    code: "HU",
    name_en: "Hungary",
    name_de: "Ungarn",
    flag: "🇭🇺",
  },
  {
    code: "IS",
    name_en: "Iceland",
    name_de: "Island",
    flag: "🇮🇸",
  },
  {
    code: "IN",
    name_en: "India",
    name_de: "Indien",
    flag: "🇮🇳",
  },
  {
    code: "ID",
    name_en: "Indonesia",
    name_de: "Indonesien",
    flag: "🇮🇩",
  },
  {
    code: "IR",
    name_en: "Iran",
    name_de: "Iran",
    flag: "🇮🇷",
  },
  {
    code: "IQ",
    name_en: "Iraq",
    name_de: "Irak",
    flag: "🇮🇶",
  },
  {
    code: "IE",
    name_en: "Ireland",
    name_de: "Irland",
    flag: "🇮🇪",
  },
  {
    code: "IM",
    name_en: "Isle of Man",
    name_de: "Isle of Man",
    flag: "🇮🇲",
  },
  {
    code: "IL",
    name_en: "Israel",
    name_de: "Israel",
    flag: "🇮🇱",
  },
  {
    code: "IT",
    name_en: "Italy",
    name_de: "Italien",
    flag: "🇮🇹",
  },
  {
    code: "CI",
    name_en: "Ivory Coast",
    name_de: "Elfenbeinküste",
    flag: "🇨🇮",
  },
  {
    code: "JM",
    name_en: "Jamaica",
    name_de: "Jamaika",
    flag: "🇯🇲",
  },
  {
    code: "JP",
    name_en: "Japan",
    name_de: "Japan",
    flag: "🇯🇵",
  },
  {
    code: "JE",
    name_en: "Jersey",
    name_de: "Jersey",
    flag: "🇯🇪",
  },
  {
    code: "JO",
    name_en: "Jordan",
    name_de: "Jordanien",
    flag: "🇯🇴",
  },
  {
    code: "KZ",
    name_en: "Kazakhstan",
    name_de: "Kasachstan",
    flag: "🇰🇿",
  },
  {
    code: "KE",
    name_en: "Kenya",
    name_de: "Kenia",
    flag: "🇰🇪",
  },
  {
    code: "KI",
    name_en: "Kiribati",
    name_de: "Kiribati",
    flag: "🇰🇮",
  },
  {
    code: "KP",
    name_en: "North Korea",
    name_de: "Nordkorea",
    flag: "🇰🇵",
  },
  {
    code: "KR",
    name_en: "South Korea",
    name_de: "Südkorea",
    flag: "🇰🇷",
  },
  {
    code: "KW",
    name_en: "Kuwait",
    name_de: "Kuwait",
    flag: "🇰🇼",
  },
  {
    code: "KG",
    name_en: "Kyrgyzstan",
    name_de: "Kirgistan",
    flag: "🇰🇬",
  },
  {
    code: "LA",
    name_en: "Laos",
    name_de: "Laos",
    flag: "🇱🇦",
  },
  {
    code: "LV",
    name_en: "Latvia",
    name_de: "Lettland",
    flag: "🇱🇻",
  },
  {
    code: "LB",
    name_en: "Lebanon",
    name_de: "Libanon",
    flag: "🇱🇧",
  },
  {
    code: "LS",
    name_en: "Lesotho",
    name_de: "Lesotho",
    flag: "🇱🇸",
  },
  {
    code: "LR",
    name_en: "Liberia",
    name_de: "Liberia",
    flag: "🇱🇷",
  },
  {
    code: "LY",
    name_en: "Libya",
    name_de: "Libyen",
    flag: "🇱🇾",
  },
  {
    code: "LI",
    name_en: "Liechtenstein",
    name_de: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    code: "LT",
    name_en: "Lithuania",
    name_de: "Litauen",
    flag: "🇱🇹",
  },
  {
    code: "LU",
    name_en: "Luxembourg",
    name_de: "Luxemburg",
    flag: "🇱🇺",
  },
  {
    code: "MO",
    name_en: "Macau",
    name_de: "Macau",
    flag: "🇲🇴",
  },
  {
    code: "MK",
    name_en: "North Macedonia",
    name_de: "Nordmazedonien",
    flag: "🇲🇰",
  },
  {
    code: "MG",
    name_en: "Madagascar",
    name_de: "Madagaskar",
    flag: "🇲🇬",
  },
  {
    code: "MW",
    name_en: "Malawi",
    name_de: "Malawi",
    flag: "🇲🇼",
  },
  {
    code: "MY",
    name_en: "Malaysia",
    name_de: "Malaysia",
    flag: "🇲🇾",
  },
  {
    code: "MV",
    name_en: "Maldives",
    name_de: "Maldiven",
    flag: "🇲🇻",
  },
  {
    code: "ML",
    name_en: "Mali",
    name_de: "Mali",
    flag: "🇲🇱",
  },
  {
    code: "MT",
    name_en: "Malta",
    name_de: "Malta",
    flag: "🇲🇹",
  },
  {
    code: "MH",
    name_en: "Marshall Islands",
    name_de: "Marshallinseln",
    flag: "🇲🇭",
  },
  {
    code: "MQ",
    name_en: "Martinique",
    name_de: "Martinique",
    flag: "🇲🇶",
  },
  {
    code: "MR",
    name_en: "Mauritania",
    name_de: "Mauretanien",
    flag: "🇲🇷",
  },
  {
    code: "MU",
    name_en: "Mauritius",
    name_de: "Mauritius",
    flag: "🇲🇺",
  },
  {
    code: "YT",
    name_en: "Mayotte",
    name_de: "Mayotte",
    flag: "🇾🇹",
  },
  {
    code: "MX",
    name_en: "Mexico",
    name_de: "Mexiko",
    flag: "🇲🇽",
  },
  {
    code: "FM",
    name_en: "Micronesia",
    name_de: "Mikronesien",
    flag: "🇫🇲",
  },
  {
    code: "MD",
    name_en: "Moldova",
    name_de: "Moldawien",
    flag: "🇲🇩",
  },
  {
    code: "MC",
    name_en: "Monaco",
    name_de: "Monaco",
    flag: "🇲🇨",
  },
  {
    code: "MN",
    name_en: "Mongolia",
    name_de: "Mongolei",
    flag: "🇲🇳",
  },
  {
    code: "ME",
    name_en: "Montenegro",
    name_de: "Montenegro",
    flag: "🇲🇪",
  },
  {
    code: "MS",
    name_en: "Montserrat",
    name_de: "Montserrat",
    flag: "🇲🇸",
  },
  {
    code: "MA",
    name_en: "Morocco",
    name_de: "Marokko",
    flag: "🇲🇦",
  },
  {
    code: "MZ",
    name_en: "Mozambique",
    name_de: "Mosambik",
    flag: "🇲🇿",
  },
  {
    code: "MM",
    name_en: "Myanmar",
    name_de: "Myanmar",
    flag: "🇲🇲",
  },
  {
    code: "NA",
    name_en: "Namibia",
    name_de: "Namibia",
    flag: "🇳🇦",
  },
  {
    code: "NR",
    name_en: "Nauru",
    name_de: "Nauru",
    flag: "🇳🇷",
  },
  {
    code: "NP",
    name_en: "Nepal",
    name_de: "Nepal",
    flag: "🇳🇵",
  },
  {
    code: "NL",
    name_en: "Netherlands",
    name_de: "Niederlande",
    flag: "🇳🇱",
  },
  {
    code: "NC",
    name_en: "New Caledonia",
    name_de: "Neukaledonien",
    flag: "🇳🇨",
  },
  {
    code: "NZ",
    name_en: "New Zealand",
    name_de: "Neuseeland",
    flag: "🇳🇿",
  },
  {
    code: "NI",
    name_en: "Nicaragua",
    name_de: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    code: "NE",
    name_en: "Niger",
    name_de: "Niger",
    flag: "🇳🇪",
  },
  {
    code: "NG",
    name_en: "Nigeria",
    name_de: "Nigeria",
    flag: "🇳🇬",
  },
  {
    code: "NU",
    name_en: "Niue",
    name_de: "Niue",
    flag: "🇳🇺",
  },
  {
    code: "NF",
    name_en: "Norfolk Island",
    name_de: "Norfolkinsel",
    flag: "🇳🇫",
  },
  {
    code: "MP",
    name_en: "Northern Mariana Islands",
    name_de: "Nördliche Marianen",
    flag: "🇲🇵",
  },
  {
    code: "NO",
    name_en: "Norway",
    name_de: "Norwegen",
    flag: "🇳🇴",
  },
  {
    code: "OM",
    name_en: "Oman",
    name_de: "Oman",
    flag: "🇴🇲",
  },
  {
    code: "PK",
    name_en: "Pakistan",
    name_de: "Pakistan",
    flag: "🇵🇰",
  },
  {
    code: "PW",
    name_en: "Palau",
    name_de: "Palau",
    flag: "🇵🇼",
  },
  {
    code: "PS",
    name_en: "Palestinian Territories",
    name_de: "Palästinensische Gebiete",
    flag: "🇵🇸",
  },
  {
    code: "PA",
    name_en: "Panama",
    name_de: "Panama",
    flag: "🇵🇦",
  },
  {
    code: "PG",
    name_en: "Papua New Guinea",
    name_de: "Papua-Neuguinea",
    flag: "🇵🇬",
  },
  {
    code: "PY",
    name_en: "Paraguay",
    name_de: "Paraguay",
    flag: "🇵🇾",
  },
  {
    code: "PE",
    name_en: "Peru",
    name_de: "Peru",
    flag: "🇵🇪",
  },
  {
    code: "PH",
    name_en: "Philippines",
    name_de: "Philippinen",
    flag: "🇵🇭",
  },
  {
    code: "PN",
    name_en: "Pitcairn Islands",
    name_de: "Pitcairninseln",
    flag: "🇵🇳",
  },
  {
    code: "PL",
    name_en: "Poland",
    name_de: "Polen",
    flag: "🇵🇱",
  },
  {
    code: "PT",
    name_en: "Portugal",
    name_de: "Portugal",
    flag: "🇵🇹",
  },
  {
    code: "PR",
    name_en: "Puerto Rico",
    name_de: "Puerto Rico",
    flag: "🇵🇷",
  },
  {
    code: "QA",
    name_en: "Qatar",
    name_de: "Katar",
    flag: "🇶🇦",
  },
  {
    code: "RE",
    name_en: "Réunion",
    name_de: "Réunion",
    flag: "🇷🇪",
  },
  {
    code: "RO",
    name_en: "Romania",
    name_de: "Rumänien",
    flag: "🇷🇴",
  },
  {
    code: "RU",
    name_en: "Russia",
    name_de: "Russland",
    flag: "🇷🇺",
  },
  {
    code: "RW",
    name_en: "Rwanda",
    name_de: "Ruanda",
    flag: "🇷🇼",
  },
  {
    code: "BL",
    name_en: "Saint Barthélemy",
    name_de: "Saint-Barthélemy",
    flag: "🇧🇱",
  },
  {
    code: "SH",
    name_en: "Saint Helena",
    name_de: "Saint Helena",
    flag: "🇸🇭",
  },
  {
    code: "KN",
    name_en: "Saint Kitts and Nevis",
    name_de: "Saint Kitts und Nevis",
    flag: "🇰🇳",
  },
  {
    code: "LC",
    name_en: "Saint Lucia",
    name_de: "Saint Lucia",
    flag: "🇱🇨",
  },
  {
    code: "MF",
    name_en: "Saint Martin",
    name_de: "Saint Martin",
    flag: "🇲🇫",
  },
  {
    code: "SX",
    name_en: "Sint Maarten",
    name_de: "Sint Maarten",
    flag: "🇸🇽",
  },
  {
    code: "SM",
    name_en: "San Marino",
    name_de: "San Marino",
    flag: "🇸🇲",
  },
  {
    code: "ST",
    name_en: "São Tomé and Príncipe",
    name_de: "São Tomé und Príncipe",
    flag: "🇸🇹",
  },
  {
    code: "SA",
    name_en: "Saudi Arabia",
    name_de: "Saudi-Arabien",
    flag: "🇸🇦",
  },
  {
    code: "SN",
    name_en: "Senegal",
    name_de: "Senegal",
    flag: "🇸🇳",
  },
  {
    code: "RS",
    name_en: "Serbia",
    name_de: "Serbien",
    flag: "🇷🇸",
  },
  {
    code: "SC",
    name_en: "Seychelles",
    name_de: "Seychellen",
    flag: "🇸🇨",
  },
  {
    code: "SL",
    name_en: "Sierra Leone",
    name_de: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    code: "SG",
    name_en: "Singapore",
    name_de: "Singapur",
    flag: "🇸🇬",
  },
  {
    code: "SK",
    name_en: "Slovakia",
    name_de: "Slowakei",
    flag: "🇸🇰",
  },
  {
    code: "SI",
    name_en: "Slovenia",
    name_de: "Slowenien",
    flag: "🇸🇮",
  },
  {
    code: "SB",
    name_en: "Solomon Islands",
    name_de: "Salomonen",
    flag: "🇸🇧",
  },
  {
    code: "SO",
    name_en: "Somalia",
    name_de: "Somalia",
    flag: "🇸🇴",
  },
  {
    code: "ZA",
    name_en: "South Africa",
    name_de: "Südafrika",
    flag: "🇿🇦",
  },
  {
    code: "GS",
    name_en: "South Georgia and the South Sandwich Islands",
    name_de: "Südgeorgien und die Südlichen Sandwichinseln",
    flag: "🇬🇸",
  },
  {
    code: "KR",
    name_en: "South Korea",
    name_de: "Südkorea",
    flag: "🇰🇷",
  },
  {
    code: "SS",
    name_en: "South Sudan",
    name_de: "Südsudan",
    flag: "🇸🇸",
  },
  {
    code: "ES",
    name_en: "Spain",
    name_de: "Spanien",
    flag: "🇪🇸",
  },
  {
    code: "LK",
    name_en: "Sri Lanka",
    name_de: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    code: "SD",
    name_en: "Sudan",
    name_de: "Sudan",
    flag: "🇸🇩",
  },
  {
    code: "SR",
    name_en: "Suriname",
    name_de: "Suriname",
    flag: "🇸🇷",
  },
  {
    code: "SJ",
    name_en: "Svalbard and Jan Mayen",
    name_de: "Svalbard und Jan Mayen",
    flag: "🇸🇯",
  },
  {
    code: "SE",
    name_en: "Sweden",
    name_de: "Schweden",
    flag: "🇸🇪",
  },
  {
    code: "CH",
    name_en: "Switzerland",
    name_de: "Schweiz",
    flag: "🇨🇭",
  },
  {
    code: "SY",
    name_en: "Syria",
    name_de: "Syrien",
    flag: "🇸🇾",
  },
  {
    code: "TW",
    name_en: "Taiwan",
    name_de: "Taiwan",
    flag: "🇹🇼",
  },
  {
    code: "TJ",
    name_en: "Tajikistan",
    name_de: "Tadschikistan",
    flag: "🇹🇯",
  },
  {
    code: "TZ",
    name_en: "Tanzania",
    name_de: "Tansania",
    flag: "🇹🇿",
  },
  {
    code: "TH",
    name_en: "Thailand",
    name_de: "Thailand",
    flag: "🇹🇭",
  },
  {
    code: "TL",
    name_en: "Timor-Leste",
    name_de: "Osttimor",
    flag: "🇹🇱",
  },
  {
    code: "TG",
    name_en: "Togo",
    name_de: "Togo",
    flag: "🇹🇬",
  },
  {
    code: "TK",
    name_en: "Tokelau",
    name_de: "Tokelau",
    flag: "🇹🇰",
  },
  {
    code: "TO",
    name_en: "Tonga",
    name_de: "Tonga",
    flag: "🇹🇴",
  },
  {
    code: "TT",
    name_en: "Trinidad and Tobago",
    name_de: "Trinidad und Tobago",
    flag: "🇹🇹",
  },
  {
    code: "TN",
    name_en: "Tunisia",
    name_de: "Tunesien",
    flag: "🇹🇳",
  },
  {
    code: "TR",
    name_en: "Turkey",
    name_de: "Türkei",
    flag: "🇹🇷",
  },
  {
    code: "TM",
    name_en: "Turkmenistan",
    name_de: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    code: "TC",
    name_en: "Turks and Caicos Islands",
    name_de: "Turks- und Caicosinseln",
    flag: "🇹🇨",
  },
  {
    code: "TV",
    name_en: "Tuvalu",
    name_de: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    code: "UG",
    name_en: "Uganda",
    name_de: "Uganda",
    flag: "🇺🇬",
  },
  {
    code: "UA",
    name_en: "Ukraine",
    name_de: "Ukraine",
    flag: "🇺🇦",
  },
  {
    code: "AE",
    name_en: "United Arab Emirates",
    name_de: "Vereinigte Arabische Emirate",
    flag: "🇦🇪",
  },
  {
    code: "GB",
    name_en: "United Kingdom",
    name_de: "Vereinigtes Königreich",
    flag: "🇬🇧",
  },
  {
    code: "US",
    name_en: "United States",
    name_de: "Vereinigte Staaten",
    flag: "🇺🇸",
  },
  {
    code: "UY",
    name_en: "Uruguay",
    name_de: "Uruguay",
    flag: "🇺🇾",
  },
  {
    code: "UZ",
    name_en: "Uzbekistan",
    name_de: "Usbekistan",
    flag: "🇺🇿",
  },
  {
    code: "VU",
    name_en: "Vanuatu",
    name_de: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    code: "VA",
    name_en: "Vatican City",
    name_de: "Vatikanstadt",
    flag: "🇻🇦",
  },
  {
    code: "VE",
    name_en: "Venezuela",
    name_de: "Venezuela",
    flag: "🇻🇪",
  },
  {
    code: "VN",
    name_en: "Vietnam",
    name_de: "Vietnam",
    flag: "🇻🇳",
  },
  {
    code: "WF",
    name_en: "Wallis and Futuna",
    name_de: "Wallis und Futuna",
    flag: "🇼🇫",
  },
  {
    code: "EH",
    name_en: "Western Sahara",
    name_de: "Westsahara",
    flag: "🇪🇭",
  },
  {
    code: "YE",
    name_en: "Yemen",
    name_de: "Jemen",
    flag: "🇾🇪",
  },
  {
    code: "ZM",
    name_en: "Zambia",
    name_de: "Sambia",
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    name_en: "Zimbabwe",
    name_de: "Simbabwe",
    flag: "🇿🇼",
  },
];
